## Pipeline para tratamento das imagens de treinamento do modelo

In [1]:
import os
import numpy as np
import cv2 as ocv
import pandas as pd

In [2]:
SIZE_JUMP = len([f for f in os.listdir(f"{os.getcwd()}\\raw\\jumping")])
SIZE_NOTJUMP = len([f for f in os.listdir(f"{os.getcwd()}\\raw\\no-jumping")])

In [3]:
print(SIZE_JUMP)
print(SIZE_NOTJUMP)

68
85

In [4]:
global rows

for p in range(SIZE_JUMP):
    img = ocv.imread(f"{os.getcwd()}\\raw\\jumping\\image_{p}.png")
    img = ocv.resize(img, None, fx=0.3, fy=0.3)
    img = ocv.cvtColor(img, ocv.COLOR_BGR2GRAY)
    
    x = img.shape
    reshaped = np.reshape(img, (1,x[0] * x[1]))

    if p == 0:
        rows = reshaped
    else:
        rows = np.concatenate((rows, reshaped))

In [5]:
for p in range(SIZE_NOTJUMP):
    img = ocv.imread(f"{os.getcwd()}\\raw\\no-jumping\\image_{p}.png")
    img = ocv.resize(img, None, fx=0.3, fy=0.3)
    img = ocv.cvtColor(img, ocv.COLOR_BGR2GRAY)
    
    x = img.shape
    reshaped = np.reshape(img, (1, x[0] * x[1]))

    rows = np.concatenate((rows, reshaped))

In [6]:
csv = pd.DataFrame(rows)
csv

,0,1,2,3,4,5,6,7,8,9,...,27638,27639,27640,27641,27642,27643,27644,27645,27646,27647
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
149,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
150,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
151,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
152,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
rotulos = ["Jumping"] * SIZE_JUMP + ["Not Jumping"] * SIZE_NOTJUMP 
csv = pd.concat([csv, pd.DataFrame(rotulos, columns=["Class"])], axis=1)
csv

,0,1,2,3,4,5,6,7,8,9,...,27639,27640,27641,27642,27643,27644,27645,27646,27647,Class
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Jumping
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Jumping
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Jumping
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Jumping
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Jumping
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Not Jumping
149,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Not Jumping
150,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Not Jumping
151,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Not Jumping
152,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Not Jumping

In [8]:
csv.to_csv("ans.csv")